/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import dao.LinhKienDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.LinhKien;

/**
 *
 * @author Admin
 */
public class FindLK extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    boolean isLoai = true;
    /** Creates new form FindLK */
    public FindLK() {
        initComponents();
        cbLst.setVisible(false);
        dtm = (DefaultTableModel) tbTT.getModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTT = new javax.swing.JTable();
        btnE = new javax.swing.JButton();
        cbLst = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setTitle("Tìm thông tin linh kiện");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tìm kiếm linh kiện");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );

        btnFind.setText("Tìm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        tbTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên linh kiện", "Bảo hành", "Nhà sản xuất", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tbTT);

        btnE.setText("Quay lại");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        cbLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String txtFind = tfFind.getText();
        if (txtFind.trim().isEmpty()){
            JOptionPane.showMessageDialog(tbTT, "Xin mời nhập thông tin cần tìm", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ArrayList<LinhKien> lstLK = new ArrayList<LinhKien>();
        ArrayList<String> lst;
        cbLst.removeAllItems();
        cbLst.addItem("- none -");
        boolean display = false; // none
        try {
            if (txtFind.toLowerCase().startsWith("type:")) {
                display = true;
                isLoai = true;
                lst = LinhKienDAO.lstTenLoai();
                lst.forEach(loai -> {
                    this.cbLst.addItem(loai);
                });
            }else if (txtFind.toLowerCase().startsWith("nsx:")) {
                display = true;
                isLoai = false;
                lst = LinhKienDAO.lstNSX();
                lst.forEach(nsx -> {
                    this.cbLst.addItem(nsx);
                });
            }else {
                display = false;
                lstLK = LinhKienDAO.showListLK(txtFind);
            }
        } catch (Exception e) {
        }
        cbLst.setVisible(display);
        if (display) return;
        dtm.setRowCount(0);
        lstLK.forEach(lk -> {
            Vector<Object> v = new Vector<Object>();
            v.add(lk.getMaLK());
            v.add(lk.getTenLK());
            v.add(String.format("%d %s", lk.getTgBaoHanh(), "tháng"));
            v.add(lk.getNsx());
            v.add(lk.getSlTonKho());
            dtm.addRow(v);
        });
    }//GEN-LAST:event_btnFindActionPerformed

    private void cbLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLstActionPerformed
        ArrayList<LinhKien> lstLK = new ArrayList<LinhKien>();
        try {
            if (isLoai)
                lstLK = LinhKienDAO.showListLK_LLK(cbLst.getSelectedItem().toString());
            else 
                lstLK = LinhKienDAO.showListLK_NSX(cbLst.getSelectedItem().toString());

            dtm.setRowCount(0);
            lstLK.forEach(lk -> {
                Vector<Object> v = new Vector<Object>();
                v.add(lk.getMaLK());
                v.add(lk.getTenLK());
                v.add(String.format("%d %s", lk.getTgBaoHanh(), "tháng"));
                v.add(lk.getNsx());
                v.add(lk.getSlTonKho());
                dtm.addRow(v);
            });
        } catch (Exception e) {
//            e.printStackTrace();
        }
    }//GEN-LAST:event_cbLstActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cbLst;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTT;
    private javax.swing.JTextField tfFind;
    // End of variables declaration//GEN-END:variables

}
