/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


/**
 *
 * @author Admin
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuCN = new javax.swing.JMenu();
        mnuTTLK = new javax.swing.JMenuItem();
        mnuFindLK = new javax.swing.JMenuItem();
        mnuFindNV = new javax.swing.JMenuItem();
        mnuTKDT = new javax.swing.JMenuItem();
        mnuTKNV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCN.setMnemonic('f');
        mnuCN.setText("Chức năng");

        mnuTTLK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuTTLK.setMnemonic('o');
        mnuTTLK.setText("Thông tin linh kiện");
        mnuTTLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTTLKActionPerformed(evt);
            }
        });
        mnuCN.add(mnuTTLK);

        mnuFindLK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuFindLK.setMnemonic('s');
        mnuFindLK.setText("Tìm linh kiện");
        mnuFindLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFindLKActionPerformed(evt);
            }
        });
        mnuCN.add(mnuFindLK);

        mnuFindNV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuFindNV.setMnemonic('a');
        mnuFindNV.setText("Tìm nhân viên");
        mnuFindNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFindNVActionPerformed(evt);
            }
        });
        mnuCN.add(mnuFindNV);

        mnuTKDT.setText("Thống Kê Doanh Thu Cty");
        mnuTKDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKDTActionPerformed(evt);
            }
        });
        mnuCN.add(mnuTKDT);

        mnuTKNV.setText("Thống Kê Nhân Viên");
        mnuTKNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKNVActionPerformed(evt);
            }
        });
        mnuCN.add(mnuTKNV);
        mnuCN.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mnuCN.add(exitMenuItem);

        menuBar.add(mnuCN);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuTTLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTTLKActionPerformed
        ThongTinLK ttlk = new ThongTinLK(this);
        ttlk.setVisible(true);
        desktopPane.add(ttlk);
    }//GEN-LAST:event_mnuTTLKActionPerformed

    private void mnuFindNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFindNVActionPerformed
        FindNV fNV = new FindNV();
        fNV.setVisible(true);
        desktopPane.add(fNV);
    }//GEN-LAST:event_mnuFindNVActionPerformed

    private void mnuFindLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFindLKActionPerformed
        FindLK flk = new FindLK();
        flk.setVisible(true);
        desktopPane.add(flk);
    }//GEN-LAST:event_mnuFindLKActionPerformed

    private void mnuTKDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKDTActionPerformed
        ThongKeDTCT tkdtct = new ThongKeDTCT();
        tkdtct.setVisible(true);
        desktopPane.add(tkdtct);
    }//GEN-LAST:event_mnuTKDTActionPerformed

    private void mnuTKNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKNVActionPerformed
        ThongKeNhanVien tknv = new ThongKeNhanVien();
        tknv.setVisible(true);
        desktopPane.add(tknv);
    }//GEN-LAST:event_mnuTKNVActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        new Content(this, true).setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About(this, true).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuCN;
    private javax.swing.JMenuItem mnuFindLK;
    private javax.swing.JMenuItem mnuFindNV;
    private javax.swing.JMenuItem mnuTKDT;
    private javax.swing.JMenuItem mnuTKNV;
    private javax.swing.JMenuItem mnuTTLK;
    // End of variables declaration//GEN-END:variables

}
