/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dataprovider.SQLServerProvider;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import pojo.JasperConnect;

/**
 *
 * @author Admin
 */
public class ThongKeDTCT extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKeDTCT
     */
    public ThongKeDTCT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        btnXDT = new javax.swing.JButton();
        btnE = new javax.swing.JButton();

        setTitle("Thống kê doanh thu công ty");

        jLabel1.setText("Nhập năm: ");

        btnXDT.setText("Xuất");
        btnXDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXDTActionPerformed(evt);
            }
        });

        btnE.setText("Thoát");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXDT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXDT)
                    .addComponent(btnE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXDTActionPerformed
        try {
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("year", Integer.parseInt(txtN.getText())); // truyền giá trị nhập        
            map.put("SUBREPORT_DIR", JasperConnect.getPathRootToReport());// lấy đường dẫn file subreport
            
            JasperConnect jc = new JasperConnect();
            String reportFile = "ThongKeDoanhThu.jrxml";
            
            SQLServerProvider provider = new SQLServerProvider();
            
            provider.open();
            jc.genarateReport(reportFile, map, provider.getConn());
            provider.close();
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btnXDTActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnXDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
