CREATE TABLE LOAILK
(
	MALOAI VARCHAR(10) NOT NULL,
	TENLOAI NVARCHAR(50),
	CONSTRAINT PK_LOAILK PRIMARY KEY (MALOAI)
)
CREATE TABLE LINHKIEN
(
	MALK VARCHAR(10) NOT NULL,
	TENLK NVARCHAR(50),
	NGAYSX DATE,
	TGBH INT, -- thời gian bảo hành
	MALOAI VARCHAR(10),
	NSX NVARCHAR(50), -- nhà sản xuất
	DVT NVARCHAR(30), -- đơn vị tính
	CONSTRAINT PK_LINHKIEN PRIMARY KEY (MALK),
	CONSTRAINT FK_LINHKIEN_LOAILK FOREIGN KEY (MALOAI)  REFERENCES LOAILK(MALOAI)
)
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) NOT NULL,
	TENKH NVARCHAR(50),
	DCHI NVARCHAR(MAX),
	DTHOAI VARCHAR(15),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)
CREATE TABLE HOADON -- tổng kết hóa đơn xuất hàng
(
	MAHD VARCHAR(10) NOT NULL,
	NGAYHD DATE, -- default getdate()
	MAKH VARCHAR(10),
	TRIGIA MONEY, -- trigger
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
CREATE TABLE CHITIETHD  -- bill
(
	MAHD VARCHAR(10) NOT NULL,
	MALK VARCHAR(10) NOT NULL,
	SOLUONG INT,
	DONGIA MONEY,
	CONSTRAINT PK_CHITIETHD PRIMARY KEY (MAHD,MALK),
	CONSTRAINT FK_CHITIETHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETHD_LINHKIEN FOREIGN KEY (MALK) REFERENCES LINHKIEN(MALK)
)
CREATE TABLE PHIEUNHAP -- nhập hàng
(
  MAPN VARCHAR(10) NOT NULL,
  NGAYNHAP DATE, -- default getdate()
  TRIGIA MONEY -- trigger
  CONSTRAINT PK_PN PRIMARY KEY (MAPN)
)
CREATE TABLE CHITIETPN
(
  MAPN VARCHAR(10) NOT NULL,
  MALK VARCHAR(10) NOT NULL,
  SOLUONG INT,
  DONGIA MONEY,
  CONSTRAINT PK_CTPN PRIMARY KEY (MAPN, MALK),
  CONSTRAINT FK_CTPN_LK FOREIGN KEY (MALK) REFERENCES LINHKIEN(MALK),
  CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN)
)
